#!/usr/bin/env python

import sys
import os
sys.path.insert(0, os.path.realpath( sys.path[0] ))

from etc.music_deduplicator import MusicDeduplicator
from optparse import OptionParser

def main():
    """ Deduplicate music files """
    parser = OptionParser()
    parser.add_option("-d", "--directory", dest="dir",
                      help="Directory in which to dedupe music files")
    parser.add_option("-r", "--recursive", dest="dir", default=True,
                      help="Search recursively in the directory. Defaults to True")

    (options, args) = parser.parse_args()

    _check_args( options, args )

    deduplicator = MusicDeduplicator()
    deduplicator.dedupe()

def _check_args( options, args ):
    print "Options: {0}".format(options)
    print "Args: {0}".format(args)

if __name__ == '__main__':
    main()
