#!/usr/bin/env python

from dedupe.music import Deduplicator
from optparse import OptionParser

def main():
    """ Deduplicate music files """
    parser = OptionParser()
    parser.add_option("-d", "--directory", dest="dir",
                      help="Directory in which to dedupe music files")
    parser.add_option("-r", "--recursive", dest="dir", default=True
                      help="Search recursively in the directory. Defaults to True")

    (options, args) = parser.parse_args()

    deduplicator = Deduplicator( options, args )
    deduplicator.dedupe()

if __name__ == '__main__':
    main()
