#!/usr/bin/env python

import sys
import os
sys.path.insert(0, os.path.realpath( sys.path[0] ))

from etc.music_deduplicator import MusicDeduplicator
from optparse import OptionParser

def main():
    """ Deduplicate music files """
    parser = OptionParser()
    parser.add_option("-d", "--directory", dest="path",
        help="Directory in which to (recursively) dedupe music files")

    (options, args) = parser.parse_args()
    full_path = _get_full_path( parser, options )

    deduplicator = MusicDeduplicator()
    deduplicator.set_directory( full_path )
    deduplicator.dedupe()

def _get_full_path( parser, options ):
    if not (options.path and os.path.isdir(options.path) ):
        parser.print_help()
        print "Please specify a valid directory for music file deduplication."
        sys.exit()
    return os.path.abspath( options.path )

if __name__ == '__main__':
    main()
